### ISSUE TITLE
v0.4.0 not in npm repository

### ISSUE THREAD

**Issue by cvetand** [temando/serverless-openapi-documentation#23]
Hi, the latest version I'm able to pull in from npm is v0.3.0. Is there a timeframe for pushing v0.4.0 to npm? 

I'm looking to pull a bugfix (https://github.com/temando/serverless-openapi-documentation/pull/16) which is in the newer version. Trying to specify using the git commit through package.json is giving me issues as serverless isn't recognizing it as a plugin.

**Comment by hsz** [comment]
cc @nfour @temando @kivlor

**Comment by nfour** [comment]
#21 #23

Looks like there was issues with the travis deploy step which is fixed, but now the NPM_TOKEN is expired - going to have to refresh this on monday.

@zyrorl

**Comment by hsz** [comment]
@nfour any progress?

**Comment by kivlor** [comment]
published.
